# demo project no issue 
spring:
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: create-drop
  datasource:
    username: sa
    password:
    url: jdbc:h2:mem:appdb
data:
   learning: git 
newdata:
        learning2: git

        learning3:git

        biking4
