# demo project no issue 
spring:
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: create-drop
  datasource:
    username: sa
    password:
    url: jdbc:h2:mem:appdb
data:
   learning: git
     I love learning Git
     I found my interest I am glad I did.
