# demo project no issue 
spring:
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: create-drop
  datasource:
    username: sa
    password:
    url: jdbc:h2:mem:appdb
data:
   learning: git
     I am learning Git
     It is very interesting as opposed to what I expected.
